# Copyright (c) 2013 SIOS Technology Corp.  All rights reserved.

# This file is part of FVORGE.

# FVORGE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# FVORGE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with FVORGE.  If not, see <http://www.gnu.org/licenses/>.

bin/fvorge-deploy.pl /opt/fvorge/bin/fvorge-deploy
bin/fvorge-lio.pl /opt/fvorge/bin/fvorge-lio
bin/sp-erase.pl /opt/fvorge/bin/sp-erase
bin/sp-setup.pl /opt/fvorge/bin/sp-setup

etc/init.d/fvorge.sh /etc/init.d/fvorge

lib/OVF/example-ovf-defaults.xml /opt/fvorge/lib/OVF/example-ovf-defaults.xml
lib/OVF/fvorge-ovf-snippet.xml /opt/fvorge/lib/OVF/fvorge-ovf-snippet.xml
lib/OVF/clusters/03-06-04-01/200/01 /opt/fvorge/lib/OVF/clusters/03-06-04-01/200/01
lib/OVF/clusters/03-06-04-01/200/02 /opt/fvorge/lib/OVF/clusters/03-06-04-01/200/02
lib/OVF/clusters/03-06-04-01/200/02 /opt/fvorge/lib/OVF/clusters/03-06-04-01/200/03
lib/OVF/clusters/03-06-04-01/200/02 /opt/fvorge/lib/OVF/clusters/03-06-04-01/200/04
lib/OVF/fvorge-deploy-examples/batch_4node.cf /opt/fvorge/lib/OVF/fvorge-deploy-examples/batch_4node.cf
lib/OVF/fvorge-deploy-examples/batch-fvorge.pl /opt/fvorge/lib/OVF/fvorge-deploy-examples/batch-fvorge

lib/perl/Linux/Distribution.pm /opt/fvorge/lib/perl/Linux/Distribution.pm

lib/perl/LIO/Module.pm /opt/fvorge/lib/perl/LIO/Module.pm
lib/perl/LIO/Vars.pm /opt/fvorge/lib/perl/LIO/Vars.pm

lib/perl/OVF/State.pm /opt/fvorge/lib/perl/OVF/State.pm
lib/perl/OVF/VApp.pm /opt/fvorge/lib/perl/OVF/VApp.pm

lib/perl/OVF/Automation/Module.pm /opt/fvorge/lib/perl/OVF/Automation/Module.pm
lib/perl/OVF/Automation/Vars.pm /opt/fvorge/lib/perl/OVF/Automation/Vars.pm

lib/perl/OVF/Custom/Module.pm /opt/fvorge/lib/perl/OVF/Custom/Module.pm

lib/perl/OVF/Manage/Directories.pm /opt/fvorge/lib/perl/OVF/Manage/Directories.pm
lib/perl/OVF/Manage/Files.pm /opt/fvorge/lib/perl/OVF/Manage/Files.pm
lib/perl/OVF/Manage/Groups.pm /opt/fvorge/lib/perl/OVF/Manage/Groups.pm
lib/perl/OVF/Manage/Init.pm /opt/fvorge/lib/perl/OVF/Manage/Init.pm
lib/perl/OVF/Manage/Network.pm /opt/fvorge/lib/perl/OVF/Manage/Network.pm
lib/perl/OVF/Manage/Packages.pm /opt/fvorge/lib/perl/OVF/Manage/Packages.pm
lib/perl/OVF/Manage/Storage.pm /opt/fvorge/lib/perl/OVF/Manage/Storage.pm
lib/perl/OVF/Manage/Tasks.pm /opt/fvorge/lib/perl/OVF/Manage/Tasks.pm
lib/perl/OVF/Manage/Users.pm /opt/fvorge/lib/perl/OVF/Manage/Users.pm

lib/perl/OVF/Network/Module.pm /opt/fvorge/lib/perl/OVF/Network/Module.pm
lib/perl/OVF/Network/Vars.pm /opt/fvorge/lib/perl/OVF/Network/Vars.pm

lib/perl/OVF/Service/App/NFS/Module.pm /opt/fvorge/lib/perl/OVF/Service/App/NFS/Module.pm
lib/perl/OVF/Service/App/NFS/Packages.pm /opt/fvorge/lib/perl/OVF/Service/App/NFS/Packages.pm
lib/perl/OVF/Service/App/NFS/Vars.pm /opt/fvorge/lib/perl/OVF/Service/App/NFS/Vars.pm
lib/perl/OVF/Service/App/Samba/Module.pm /opt/fvorge/lib/perl/OVF/Service/App/Samba/Module.pm
lib/perl/OVF/Service/App/Samba/Packages.pm /opt/fvorge/lib/perl/OVF/Service/App/Samba/Packages.pm
lib/perl/OVF/Service/App/Samba/Vars.pm /opt/fvorge/lib/perl/OVF/Service/App/Samba/Vars.pm
lib/perl/OVF/Service/Database/MySQL/Module.pm /opt/fvorge/lib/perl/OVF/Service/Database/MySQL/Module.pm
lib/perl/OVF/Service/Database/MySQL/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Database/MySQL/Packages.pm
lib/perl/OVF/Service/Database/MySQL/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Database/MySQL/Vars.pm
lib/perl/OVF/Service/Database/Oracle/Module.pm /opt/fvorge/lib/perl/OVF/Service/Database/Oracle/Module.pm
lib/perl/OVF/Service/Database/Oracle/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Database/Oracle/Vars.pm
lib/perl/OVF/Service/Database/PostgreSQL/Module.pm /opt/fvorge/lib/perl/OVF/Service/Database/PostgreSQL/Module.pm
lib/perl/OVF/Service/Database/PostgreSQL/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Database/PostgreSQL/Packages.pm
lib/perl/OVF/Service/Database/PostgreSQL/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Database/PostgreSQL/Vars.pm
lib/perl/OVF/Service/Database/SAPDB/Module.pm /opt/fvorge/lib/perl/OVF/Service/Database/SAPDB/Module.pm
lib/perl/OVF/Service/Database/SAPDB/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Database/SAPDB/Vars.pm
lib/perl/OVF/Service/Database/Sybase/Module.pm /opt/fvorge/lib/perl/OVF/Service/Database/Sybase/Module.pm
lib/perl/OVF/Service/Database/Sybase/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Database/Sybase/Vars.pm
lib/perl/OVF/Service/Graphic/XServer/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Graphic/XServer/Packages.pm
lib/perl/OVF/Service/Graphic/XServer/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Graphic/XServer/Vars.pm
lib/perl/OVF/Service/Locale/Module.pm /opt/fvorge/lib/perl/OVF/Service/Locale/Module.pm
lib/perl/OVF/Service/Locale/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Locale/Packages.pm
lib/perl/OVF/Service/Locale/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Locale/Vars.pm
lib/perl/OVF/Service/Report/SNMP/Module.pm /opt/fvorge/lib/perl/OVF/Service/Report/SNMP/Module.pm
lib/perl/OVF/Service/Report/SNMP/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Report/SNMP/Packages.pm
lib/perl/OVF/Service/Report/SNMP/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Report/SNMP/Vars.pm
lib/perl/OVF/Service/Report/Syslog/Module.pm /opt/fvorge/lib/perl/OVF/Service/Report/Syslog/Module.pm
lib/perl/OVF/Service/Report/Syslog/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Report/Syslog/Vars.pm
lib/perl/OVF/Service/Repository/Module.pm /opt/fvorge/lib/perl/OVF/Service/Repository/Module.pm
lib/perl/OVF/Service/Repository/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Repository/Vars.pm
lib/perl/OVF/Service/Security/AppArmor/Module.pm /opt/fvorge/lib/perl/OVF/Service/Security/AppArmor/Module.pm
lib/perl/OVF/Service/Security/AppArmor/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Security/AppArmor/Vars.pm
lib/perl/OVF/Service/Security/Firewall/Module.pm /opt/fvorge/lib/perl/OVF/Service/Security/Firewall/Module.pm
lib/perl/OVF/Service/Security/Firewall/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Security/Firewall/Vars.pm
lib/perl/OVF/Service/Security/PAM/LDAP/Module.pm /opt/fvorge/lib/perl/OVF/Service/Security/PAM/LDAP/Module.pm
lib/perl/OVF/Service/Security/PAM/LDAP/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Security/PAM/LDAP/Packages.pm
lib/perl/OVF/Service/Security/PAM/LDAP/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Security/PAM/LDAP/Vars.pm
lib/perl/OVF/Service/Security/SELINUX/Module.pm /opt/fvorge/lib/perl/OVF/Service/Security/SELINUX/Module.pm
lib/perl/OVF/Service/Security/SELINUX/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Security/SELINUX/Vars.pm
lib/perl/OVF/Service/Security/SSH/Apply.pm /opt/fvorge/lib/perl/OVF/Service/Security/SSH/Apply.pm
lib/perl/OVF/Service/Security/SSH/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Security/SSH/Vars.pm
lib/perl/OVF/Service/Storage/ISCSI/Module.pm /opt/fvorge/lib/perl/OVF/Service/Storage/ISCSI/Module.pm
lib/perl/OVF/Service/Storage/ISCSI/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Storage/ISCSI/Packages.pm
lib/perl/OVF/Service/Storage/ISCSI/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Storage/ISCSI/Vars.pm
lib/perl/OVF/Service/Storage/Multipath/Module.pm /opt/fvorge/lib/perl/OVF/Service/Storage/Multipath/Module.pm
lib/perl/OVF/Service/Storage/Multipath/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Storage/Multipath/Packages.pm
lib/perl/OVF/Service/Storage/Multipath/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Storage/Multipath/Vars.pm
lib/perl/OVF/Service/Time/NTP/Module.pm /opt/fvorge/lib/perl/OVF/Service/Time/NTP/Module.pm
lib/perl/OVF/Service/Time/NTP/Packages.pm /opt/fvorge/lib/perl/OVF/Service/Time/NTP/Packages.pm
lib/perl/OVF/Service/Time/NTP/Vars.pm /opt/fvorge/lib/perl/OVF/Service/Time/NTP/Vars.pm

lib/perl/OVF/SIOS/Automation/Module.pm /opt/fvorge/lib/perl/OVF/SIOS/Automation/Module.pm
lib/perl/OVF/SIOS/Automation/Packages.pm /opt/fvorge/lib/perl/OVF/SIOS/Automation/Packages.pm
lib/perl/OVF/SIOS/Automation/Vars.pm /opt/fvorge/lib/perl/OVF/SIOS/Automation/Vars.pm
lib/perl/OVF/SIOS/Prerequisites/Packages.pm /opt/fvorge/lib/perl/OVF/SIOS/Prerequisites/Packages.pm
lib/perl/OVF/SIOS/Prerequisites/Vars.pm /opt/fvorge/lib/perl/OVF/SIOS/Prerequisites/Vars.pm
lib/perl/OVF/SIOS/Product/Module.pm /opt/fvorge/lib/perl/OVF/SIOS/Product/Module.pm
lib/perl/OVF/SIOS/Product/Vars.pm /opt/fvorge/lib/perl/OVF/SIOS/Product/Vars.pm

lib/perl/OVF/Storage/Filesystems/Module.pm /opt/fvorge/lib/perl/OVF/Storage/Filesystems/Module.pm
lib/perl/OVF/Storage/Filesystems/Vars.pm /opt/fvorge/lib/perl/OVF/Storage/Filesystems/Vars.pm
lib/perl/OVF/Storage/LVM/Module.pm /opt/fvorge/lib/perl/OVF/Storage/LVM/Module.pm
lib/perl/OVF/Storage/LVM/Vars.pm /opt/fvorge/lib/perl/OVF/Storage/LVM/Vars.pm

lib/perl/OVF/Vars/Common.pm /opt/fvorge/lib/perl/OVF/Vars/Common.pm
lib/perl/OVF/Vars/Common.pm /opt/fvorge/lib/perl/OVF/Vars/ovf-generic-template.ovf

lib/perl/SIOS/ArkVars.pm /opt/fvorge/lib/perl/SIOS/ArkVars.pm
lib/perl/SIOS/BuildVars.pm /opt/fvorge/lib/perl/SIOS/BuildVars.pm
lib/perl/SIOS/CommonVars.pm /opt/fvorge/lib/perl/SIOS/CommonVars.pm
lib/perl/SIOS/LicenseVars.pm /opt/fvorge/lib/perl/SIOS/LicenseVars.pm
lib/perl/SIOS/Logger.pm /opt/fvorge/lib/perl/SIOS/Logger.pm
lib/perl/SIOS/Product.pm /opt/fvorge/lib/perl/SIOS/Product.pm
lib/perl/SIOS/SysInfo.pm /opt/fvorge/lib/perl/SIOS/SysInfo.pm

lib/repos/rhel-fvorge.repo /opt/fvorge/lib/repos/rhel-fvorge.repo
lib/repos/sles-fvorge.repo /opt/fvorge/lib/repos/sles-fvorge.repo

lib/sios/qa/fill-cifs.pl /opt/fvorge/lib/sios/qa/fill-cifs
lib/sios/qa/fill-nfs.pl /opt/fvorge/lib/sios/qa/fill-nfs
lib/sios/qa/random-writers.pl /opt/fvorge/lib/sios/qa/random-writers

lib/sios/product/sps/interfacelist.sh /opt/fvorge/lib/sios/product/sps/interfacelist
lib/sios/product/sps/devicenames.sh /opt/fvorge/lib/sios/product/sps/devicenames

lib/VMware/install-tools/centos5.sh /opt/fvorge/lib/VMware/install-tools/centos5
lib/VMware/install-tools/centos6.sh /opt/fvorge/lib/VMware/install-tools/centos6
lib/VMware/install-tools/rhel5.sh /opt/fvorge/lib/VMware/install-tools/rhel5
lib/VMware/install-tools/rhel6.sh /opt/fvorge/lib/VMware/install-tools/rhel6
lib/VMware/install-tools/sles10.sh /opt/fvorge/lib/VMware/install-tools/sles10
lib/VMware/install-tools/sles11sp1.sh /opt/fvorge/lib/VMware/install-tools/sles11sp1
lib/VMware/install-tools/sles11sp2.sh /opt/fvorge/lib/VMware/install-tools/sles11sp2
lib/VMware/install-tools/keys/VMWARE-PACKAGING-GPG-DSA-KEY.pub /opt/fvorge/lib/VMware/install-tools/keys/VMWARE-PACKAGING-GPG-DSA-KEY.pub
lib/VMware/install-tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub /opt/fvorge/lib/VMware/install-tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub
lib/VMware/contrib/remove_vm.pl /opt/fvorge/lib/VMware/contrib/.
lib/VMware/contrib/remove_vm.pl /opt/fvorge/lib/VMware/contrib/remove_vm.pl
lib/VMware/contrib/vmISOManagement.pl /opt/fvorge/lib/VMware/contrib/vmISOManagement.pl
lib/VMware/sdk/powerops.pl /opt/fvorge/lib/VMware/sdk/powerops.pl
lib/VMware/sdk/removabledevices.pl /opt/fvorge/lib/VMware/sdk/removabledevices.pl
lib/VMware/sdk/snapshot.pl /opt/fvorge/lib/VMware/sdk/snapshot.pl

sbin/fvorge.pl /opt/fvorge/sbin/fvorge

# 3rd Party License Content
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/80x15.png /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/80x15.png
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/camel_head.v25e738a.png /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/camel_head.v25e738a.png
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/dev.v5f7fab3.css /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/dev.v5f7fab3.css
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/element.js /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/element.js
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/external.v1.png /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/external.v1.png
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/ga.js /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/ga.js
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/jquery.corner.v84b7681.js /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/jquery.corner.v84b7681.js
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/jquery.min.js /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/jquery.min.js
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/leostyle.v8cd7532.css /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/leostyle.v8cd7532.css
lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/leo.v9872b9c.js /opt/fvorge/lib/perl/Linux/Perl\ Licensing\ -\ dev.perl.org_files/leo.v9872b9c.js

lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/191807.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/191807.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/brightedge.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/brightedge.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/buttons.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/buttons.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/downloads-tracker.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/downloads-tracker.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/elqCfg.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/elqCfg.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/elqImg.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/elqImg.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/ip.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/ip.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/ip.json /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/ip.json
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/jquery-1.8.3.min.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/jquery-1.8.3.min.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/jquery-ui.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/jquery-ui.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/jquery.url.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/jquery.url.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/klx8ltg.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/klx8ltg.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/mbox.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/mbox.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/modernizr.custom.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/modernizr.custom.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/modernizr-latest.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/modernizr-latest.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/notice /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/notice
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/oo_conf_us.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/oo_conf_us.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/oo_engine.min.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/oo_engine.min.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/placeholder.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/placeholder.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/redesign-custom.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/redesign-custom.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/respond.min.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/respond.min.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/s_code_ts.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/s_code_ts.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/selectivizr-min.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/selectivizr-min.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/svrGP.aspx /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/svrGP.aspx
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.button.carousel.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.button.carousel.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.carousel.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.carousel.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw_cust.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw_cust.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.heightmatch.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.heightmatch.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.lbcarousel.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.lbcarousel.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.lightbox.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.lightbox.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.main.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.main.js
lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.nav.js /opt/fvorge/lib/VMware/contrib/Community\ Terms\ of\ Use\ -\ United\ States_files/vmw.nav.js

lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/cc-logo.jpg /opt/fvorge/lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/cc-logo.jpg
lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/deed3.css /opt/fvorge/lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/deed3.css
lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/deed3-print.css /opt/fvorge/lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/deed3-print.css
lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/errata.js /opt/fvorge/lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/errata.js
lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/unported.png /opt/fvorge/lib/VMware/contrib/Creative\ Commons\ Legal\ Code_files/unported.png

lib/VMware/sdk/EULA /opt/fvorge/lib/VMware/sdk/EULA
lib/VMware/sdk/open_source_licenses.txt /opt/fvorge/lib/VMware/sdk/open_source_licenses.txt
lib/VMware/sdk/README.copyright /opt/fvorge/lib/VMware/sdk/README.copyright
