#!/bin/bash
# copy package contents in, in preparation for packaging
TARGET=$1
[ ! -d $TARGET ] && echo "Invalid target dir: '$TARGET'" && exit 1
SOURCE=../rpm/SOURCES
mkdir -p $TARGET/opt/fvorge
cp -a $SOURCE/* $TARGET/opt/fvorge/
