#!/bin/bash
# copy package contents in, in preparation for packaging
TARGET=$1
[ ! -d $TARGET ] && echo "Invalid target dir: '$TARGET'" && exit 1
SOURCE=../src
mkdir -p $TARGET/opt/fvorge
pushd $SOURCE >/dev/null
DIRS=$(find . -mindepth 1 -maxdepth 1 -name 'testcases' -prune -o -print)
echo copy source dirs to pkg: $DIRS
popd > /dev/null
for d in $DIRS
do
	cp -a $SOURCE/$d $TARGET/opt/fvorge/
done
